const mongoose = require('../config/dbConfig')
const { Schema } = mongoose;

const taskSchema = new Schema({
          _id: { type: String, unique: true },
          name: {
              type: String,
            required: [true, 'must provide name'],
            trim: true      
          },
          description :{              
                    type: String,
                    trim : true
          },
          completed: {
            type: Boolean,
            default: false,
          }
});
taskSchema.methods.toJSON = function () {
    const obj = this.toObject({versionKey:false}); // versionKey: false prevents the version key generated by mongodb to be displayed in the response sent.
    return obj
}

const task = mongoose.model('task',taskSchema)
module.exports = task;
